#!/usr/bin/env bash
# This script pings an IP address passed as an argument and displays usage if no argument is provided.

if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS=$1
ping -c 5 "$IP_ADDRESS"
