#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine.

# Use `ip` command to list IPv4 addresses assigned to active interfaces
ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
